### ISSUE TITLE
Containerization with Docker on a Linux Server

### ISSUE THREAD

**Issue by TheTwoBoom** [zap-docs/docs#1104]
### What topic does your proposed suggestion relate to?

Containerization with Docker

### How do you aim to structure your proposed change?

Introduction to Docker and its significance
Prerequisites for setting up Docker on a Linux Server
Step-by-step guide to installing Docker
Basic Docker commands and usage
Downloading and running Docker containers from the official Docker registry

### Could you briefly summarise the contents you plan to write about to ensure you have the appropriate technical knowledge?

Introduction to Docker: I will provide an overview of Docker and containerization, explaining their significance in modern server management.

Prerequisites: I will list the requirements and prerequisites for setting up Docker on a Linux Server, ensuring that readers are prepared to follow the guide.

Installation Guide: A step-by-step guide on how to install Docker on a Linux Server, including commands and explanations.

Basic Docker Usage: I'll cover fundamental Docker commands and concepts, such as running containers and pulling images

### What is your ZAP ID?

zap1127684

### By submitting this form, you agree that...

- [X] You have read and understood our contribution section on our documentation.
- [X] You understand our guidelines and conditions that exist.
- [X] Your suggestion is original and not a duplicate.
- [X] You have provided the correct ZAP ID.
- [X] You have answered this suggestion form to the best of your ability.
- [X] You agree to receive feedback and communicate with our ZAP docs team.
- [X] You agree to the ZAP-Hosting Contribution Program Terms & Conditions, which can be [accessed here](https://zap-hosting.com/guides/docs/contribution-terms).

**Comment by ThatGuyJacobee** [comment]
Hey there @TheTwoBoom 👋

Apologies for the slightly delayed response and thank you for showing your interest! Your idea to improve/rework the existing "installation of docker" page with our new structure and new information seems great but, some of the information you proposed in your structure does seem quite similar to the existing content.

However, I think that we could go through with this, as long as you go more in-depth and improve the guide. One way in which you could significantly improve this is by providing the installation instructions for all of our existing Linux distros (similarly to how [this recent guide from one of our contributors](https://zap-hosting.com/guides/docs/vserver-linux-databases) handles this using tabs and using // within code blocks) where instructions may differ slightly. 

I also like your idea of having a section at the end to provide a range of basic commands and usage examples, as well as providing an example of downloading and running docker containers as this has not been covered at all.

If you remain interested, feel free to work on this and submit a PR once you are ready with all of your changes! If you need any help, make sure to let us know here and follow the [contribution guide](https://zap-hosting.com/guides/docs/contribution-guidelines) where appropriate. 

Last note, since you submitted your issue recently, we are willing to provide you with an extra **15%** for your final reward as we are running a reward bonus to celebrate ZAPtember beginning today.

Many thanks!

**Comment by ThatGuyJacobee** [comment]
Hey @TheTwoBoom hope you are doing well!

Since you haven't replied yet just following up to see if you are still interested in this. Please let us know if you are still planning to work on this sometime soon. 🙂

Kind regards!
